id: P010427
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ1021
  title: 'བཀའ་གདམས་བུ་ཆོས། '
  author: ''
  volumes:
    6e9e655dad034da4b6651579bd41bf43:
      image_group_id: I1KG13504
      title: ''
      volume_number: 1
      total_pages: 642
